/* global monogatari */

// Define the messages used in the game.
monogatari.action ('message').messages ({
	'Help': {
		title: 'Help',
		subtitle: 'Some useful Links',
		body: `
			<p><a href='https://developers.monogatari.io/documentation/'>Documentation</a> - Everything you need to know.</p>
			<p><a href='https://monogatari.io/demo/'>Demo</a> - A simple Demo.</p>
		`
	}
});

// Define the notifications used in the game
monogatari.action ('notification').notifications ({
	'Welcome': {
		title: 'Welcome',
		body: 'This is the Monogatari VN Engine',
		icon: ''
	}
});

// Credits of the people involved in the creation of this awesome game
monogatari.configuration ('credits', {

});

// Define the Particles JS Configurations used in the game
monogatari.action ('particles').particles ({

});

// Define the images that will be available on your game's image gallery
monogatari.assets ('gallery', {

});

// Define the music used in the game.
monogatari.assets ('music', {

});

// Define the voice files used in the game.
monogatari.assets ('voices', {

});

// Define the sounds used in the game.
monogatari.assets ('sounds', {

});

// Define the videos used in the game.
monogatari.assets ('videos', {

});

// Define the images used in the game.
monogatari.assets ('images', {

});

// Define the backgrounds for each scene.
monogatari.assets ('scenes', {
	"cafe": "Cafe.jpg",
	"church": "Church.jpg",
	"gym": "Gym.jpg",
	"karaoke": "Karaoke.jpg",
	"onsen": "Onsen.jpg",
	"studio": "Studio.jpg",
	"chapel": "Chapel.jpg",
	"library": "Library.jpg",

});


// Define the Characters
monogatari.characters ({
	'n': {
		name: ' ',
		color: '#5bcaff'
	},
	'all': {
		name: 'All',
		color: '#5bcaff'
	},
	'q': {
		name: '???',
		color: '#5bcaff'
	},

	//Main Characters
	's': {
		name: 'Shiori',
		color: '#F890FF',
        sprites: {
            IMG: 'Shiori.png',
        }
	},
	'b': {
		name: 'Bengshan',
		color: '#FF5500',
        sprites: {
            IMG: 'Ben.png',
        }
	},
	'l': {
		name: 'Lazlow',
		color: '#F50000',
        sprites: {
            IMG: 'Lazlow.png',
        }
	},
	'a': {
		name: 'Alisha',
		color: '#FFFB00',
        sprites: {
            IMG: 'Alisha.png',
        }
	},
	'y': {
		name: 'Yingying',
		color: '#00F3FF',
        sprites: {
            IMG: 'Yingying.png',
        }
	},
	'e': {
		name: 'Ernest',
		color: '#00B708',
        sprites: {
            IMG: 'Ernest.png',
        }
	},
	'z': {
		name: 'Noelle',
		color: '#00D5C8',
        sprites: {
            IMG: 'MKZ.png',
        }
	},
	'sa': {
		name: 'Sayo',
		color: '#F894C6',
        sprites: {
            IMG: 'Sayo.png',
        }
	},
	'al': {
		name: 'Alyssa',
		color: '#A1EEFF',
        sprites: {
            IMG: 'Alyssa.png',
        }
	},
});

monogatari.script ({
	// The game starts here.
	'Start': [
		'show scene chapel with fadeIn',
		'wait 1000',
		'show character s IMG with fadeIn',
		's Hello, everyone! Thank you for your continued support over the past year of questing and for playing this visual novel!',
		"s How have things been? Have you been enjoying the stories that have been released over the past year? If so, even just a little bit, I'd be very happy.",
		"s Anyways, in celebration of the Zikariverse 4th Anniversary, we're here today to bring you some exclusive commentaries that nobody asked for.",
		"s Let us all take this celebratory chance to reflect on not only the great things of the past year but those of all four years of Zikariverse as well.",
		"s Well, then, I'll see you in the reviews. Hope you enjoy~",
		"hide character s with fadeOutRight",
		"wait 500",

		"jump Menu"
	],

	'Menu': [
		{
			'Choice': {
				'Dialog': 'n Select a commentary track',
				'Boy': {
					'Text': "Lostbelt Raising Project - Boys' Side",
					'Do': 'jump Boy'
				},
				'Girl': {
					'Text': "Lostbelt Raising Project - Girls' Side",
					'Do': 'jump Girl'
				},
				'Language': {
					'Text': "Language of Love",
					'Do': 'jump LoL'
				},
				'TULPA': {
					'Text': "TULPA",
					'Do': 'jump TULPA'
				}
			}
		}
	],

	//LBRP Boys' Side
	'Boy': [
		'show scene cafe with fadeIn',
		'wait 1000',
		"show character b IMG with fadeIn",
		"b Yo. Welcome to the All Cast Review for Lostbelt Raising Project.",
		"b I'm Camille Vladivan Andreski, the protagonist of Lostbelt Raising Project. Today, it seems like I'll be hosting this review session.",
		"hide character b with fadeOut",
		"wait 500",
		"show character l IMG with fadeIn",
		"l And I'm also here too.",
		"l Hey there, I'm Lazlow Grimmwold, the first protagonist of the Zikariverse and one of the Crypters in LRP. I'll also be joining in for this section of the All Cast Review.",
		"hide character l",
		"wait 200",
		"show character b IMG at right with fadeIn",
		"show character l IMG at left with fadeIn",
		"b Y'know, even though it's called the All Cast Review, for some reason there's only the two of us here.",
		"b Did we get the wrong location or wrong time or something? Where's everyone else?",
		"l It seems they're splitting us up into a Boys group and a Girls group for some reason, leaving just the two of us here. What's it called? Girls' Talk? I guess that's what they're going for.",
		"b Oi, oi, then what are we supposed to do? Boys' Talk? Who on earth wants to listen to that?",
		"l You don't have to tell me about that. I'd rather be having a nice conversation with a cute girl too. I'm certain all the readers immediately skipped this section and went straight to the Girls' Side.",
		"l Well, whatever. Since we're the inferior half, let's just forget the pressure and take it easy. We can just lazily do the bare minimum and call it a day.",
		"b Sounds good to me. The faster we get out of here, the better.",
		"b What do we even talk about, though? All they told us was to reflect on and discuss LBRP. I can't think of anything to say, though.",
		"l Aren't you playing the main character? Surely you have something to say about your own story.",
		"b If you're saying that, then do you have something to say? You play a role in it too.",
		"l Oh, I'm allowed to start? Very well, then, allow me to say my piece.",
		"l Ahem.",
		"show character l IMG with shake",
		"l WHAT THE HELL IS WRONG WITH THIS QUEST!?!?",
		"b Eh? Where's this coming from?",
		"l From the title of the Quest, Lostbelt Raising Project, you'd think that it'd be a quest about raising a lostbelt, right? The original pitch was that it'd be a story where the players could manage a Lostbelt as a Crypter.",
		"b Y-yeah. And that's what's been happening...",
		"l Except not! No matter how you look at it, the actual lostbelt raising portion is clearly just a backdrop for the true purpose of this Quest. It was all false advertising to hide the true content of this story.",
		"l The true identity of this quest is actually Harem Raising Project!!!",
		"b He said it. He actually pointed out the taboo topic.",
		"b Ummm, I wouldn't say that it's like that. Sure, the status of the Quest is such that it cannot be denied if one were to call it an isekai ecchi harem romcom, but surely there's more to it than that. There's plenty of Lostbelt Raising too.",
		"l Shut up! I read your story, Ben! Aren't you living it up, collecting cute girls everywhere you go? You've done nothing the whole Quest but build your harem!",
		"l I'm so jealous! I want to have a carefree story where I do nothing but flirt with cute waifus too!",
		"b Oi, are you blind? That's not all I did! I wasn't flirting the whole ti- no, I wasn't flirting at all. I did all sorts of other important Crypter stuff too. Like for example...",
		"b I, uh... I... hmmm...",
		"l See? Nothing but harem shenanigans.",
		"b Shut up! That's not true! I'm just having some trouble remembering everything I did, since it was so long ago.",
		"b But I bet if we went back and reviewed the whole quest, we'd find plenty of my accomplishments.",
		"l Fine then. Let's review the whole thing right now. This is a review session after all.",
		"l If you can convince me that you put in work besides adding girls to your haremdex, I'll do anything you want.",
		"b Fine, let's do it. I already know for a fact that I'm right. I'll show you just how good of a Crypter I am.",

		"show scene cafe with fadeIn",
		"wait 500",
		"show character b IMG at right with fadeIn",
		"show character l IMG at left with fadeIn",
		"wait 500",
		"b So? Where do we begin?",
		"l From the start, I guess. If I remember correctly, LBRP starts with you and Assassin plopping into the Lostbelt.",
		"b Ah, that's right. I remember that part. Assassin and I entered the Lostbelt for first time and were immediately shocked at the differences. After all, the sky was empty.",
		"l It does make for one visually stunning stinger. I don't think any of the other Lostbelts have as clear a visual difference as that.",
		"b After that, the two of us walked around a bit, before we ran into Yingying.",
		"l Ran into, indeed. What a dramatic way to meet your future wife. Was it love at first sight? Or in your case, it'd be love at first grope, huh. Ihihihihi.",
		"b Ugh, don't remind me. What an embarassing way to meet someone.",
		"b Anyways, it's thank to that meeting, though, that we make our way to meet the Lostbelt King, Emperor Yao. And after some negotiations, we agreed to work together to save the Lostbelt.",
		"b See? Already I've made a major accomplishment, entering a mutually-beneficial alliance with the Lostbelt King.",
		"l But ultimately, what it results in is you marrying his daughter, right? So all you really did was pick up the main heroine.",
		"b Oi. You make it sound like the only reason I'm working with Yao is to be with his daughter.",
		"l It isn't?",
		"b Of course not! I didn't even know she was a princess yet.",
		"l Well, fine, let's just move on. After the meeting with Yao, you got given a place to stay, right? By our standards, it's a slightly larger than average apartment, but it seems super luxurious by Yao standards.",
		"b Indeed, the Emperor was very generous to us, even though I didn't comply with all his demands. It shows that he has good sense about how to treat one's allies.",
		"b Oh, speaking of, right after this, I contacted the Crypters for the first time. It's the Quest's first look at all the other Crypters.",
		"l It sure is a flashy introduction for a bunch characters who won't play a part until much later.",
		"b Says the guy who wasn't even there. What on earth were you even doing back then? Were you that busy with your own Lostbelt?",
		"l Ah, no. To be honest, I just forgot about the meeting.",
		"b Oi!",
		"l Anywaaays, right after that is your marriage with the Yingying lass, right?",
		"l What a momentous occassion. It's the legendary founding of the Bengshan Harem.",
		"show character b IMG with shake",
		"b I never founded such a perverted group!",
		"l Having two heavy-hitters like Assassin and Yingying from the start puts a lot of pressure on new-gen members too. I'm afraid they won't be able to easily join in on the usual shenanigans if they're too intimidated by the original cast.",
		"b What kind of power dynamic is this group supposed to have!? I'd never sanction such a thing!",
		"l That said, you sure hit it off with Yingying rather quickly.",
		"b Well, yeah, I guess... I was really nervous getting married and all, but I ultimately decided not to make a big deal out of it and just treat her like a friend.",
		"l Which is why you chickened out of sleeping with her?",
		"b Guh! L-let's not bring that up. I get lectured about it often enough already.",
		"l Y'know, I've been wondering... you really have no defense against lewd stuff, huh?",
		"l Could it be that you've never watched porn or stuff like that before?",
		"b Wha? Of course not! Why would I watch something dirty like that!?",
		"l You've never like... jerked off before?",
		"b No! God, no! I'd never do something like that!",
		"l Ah, you really are that kind of person, huh. Well, well, that's more or less what I expected.",
		"b Mnn... let's just move on.",
		"b After that, I went on a trip with Assassin and Yingying across the country in order to look for new allies. It's there that I ended up meeting Rider and managed to convince her to work with us.",
		"l Ah, yes, Harem Member #3.",
		"b Fuck off.",
		"l Well, all said, I actually think you did pretty well here. In fact, I'd even say it's the first actually impressive thing that you do. On the outset, I would've considered you screwed based on the situation at hand.",
		"b Mn, I really barely just scrapped by. If Rider wanted to, I would've been completely killed off. It was practically an impossible situation.",
		"b In fact, based on early predictions, it was expected for this to be where I first used my ability.",
		"l Really? You were going to use Mind Break on Rider!?",
		"b Well, it's not like I was planning to. But based on the situation, it was expected that the readers would've felt the need to use it on her. Only thanks to guessing her True Name correctly at the last moment was such a fate averted.",
		"l It goes to show that it's impossible to predict how the votes will go, huh.",
		"b With Rider onboard, we then moved on to Level 4 where we ran into Saber and Lancer.",
		"l Where you did end up having to use your ability.",
		"b Yeah.............................................. unfortunately.",
		"b Once again, it was another difficult fight. At times like that, my weakness feels the most heavy.",
		"l Was there a chance of you guys avoiding the fight entirely?",
		"b Hmmm, I think, if I had said the right things, it may have been possible to negotiate a ceasefire with Saber and Lancer. But in the end, I said what I wanted to and battle became the result. And, as much as I couldn't stand it, the moment Assassin was in danger, I ended up using my ability anyways.",
		"l Huh, so there was a chance of getting a non Mind Broken Saber?",
		"b Well... yeah. Just as it was expected for Rider to become the first victim, it wasn't expected that Saber would become one. But due to my choices, it ended up getting mixed up.",
		"b Dammit... what even was I doing? If I just did things differently, I wouldn't have had to do that to Saber...",
		"b It's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault, it's all my fault",
		"l Yabai, he's gone crazy. Let's quickly change the subject.",
		"l Hey, Bengshan! What's your wife's hobby, again?",
		"b Huh? O-oh, uh, it's reading.",
		"l Reading, huh. What kind of books? Based on vibes, maybe she's the type that reads proper literature rather than pop stuff.",
		"b Actually, she mostly reads textbooks and the like. Perhaps, rather than reading, her true hobby is studying. Though I think she ocassionally reads some romance novels too.",
		"l Oho, that's unique. Then, what about you? You look like the geeky type so maybe Sci-Fi? Fantasy? It couldn't be light novels, could it?",
		"b Nah, I don't really read much fiction. If I'm going to pick up a book, it'd be to learn something. Most of my free time during my teenage years was spent with my nose in textbooks.",
		"l Ah, so basically the two of you are pretty much the same, huh? You're both studyholics. How nice, having a significant other that shares your hobbies and interests.",
		"b Oh, huh. I guess you're right. I never really thought of it like that.",
		"l Hyuu, hyuu, aren't you two the perfect couple? You might as well have been made for each other.",
		"b S-stop it. Don't say stuff like that.",
		"l Aw, come on. When you see a cute couple, don't you just feel like teasing them?",
		"b I've never really felt that before. Rather than tease them, it's more like... I want them to explode.",
		"l Oi, only future wizards like me get to explode normies. You're having a fulfilled love life, so stay in your lane.",
		"b But like... doesn't it piss you off when you see other people being happy? It's like, how dare you be in happy in front of me. Go explode already! Most people would think that, right?",
		"l No, the only one who's that screwed in the head is you. Promise me to never go on facebook or instagram. I'm pretty sure they'd cause you to have an aneurysm.",
		"b Social media's stupid anyways. I don't see the value in broadcasting your life to other people.",
		"l Oh really? I thought social media would actually be pretty useful for you.",
		"b Huh? How so? Do I look like the kya kya selfie type?",
		"l Well, it's a way to interact with people without being in-person. And well, you can't use your ability over the internet, right?",
		"b Ah. That's...",
		"b Hmmm... that could work...",
		"b Ah! No, wait, I won't fall for that! That doesn't take away how stupid social media is!",
		"l Ihihihi, you seriously considered it for a second though. Too bad. I wanted to see the Bengshan who slides into girls' DMs and asks for lewds.",
		"b What kind of person is that? If such a version of me existed, he definitely doesn't deserve to live.",
		"b Ahh, let's just drop this subject and move on. What's next?",
		"l Okie dokie!",
		"l Phew, managed to calm him down. What a pain...",
		"b Huh? What was that?",
		"l Nothing. Just thinking about how well you'd do on Tinder.",
		"b I said to drop it!",
		"b Anyways, after I was hospitalized for three weeks, I ended up having a lot to catch up on. Rider went down to Level 5 and Saber joined our team while I was asleep.",
		"l That's right. You missed the monthly Crypter meeting too. Because of that, you didn't hear about Illium until a while later.",
		"b Yeah. Which of course brings us to... Alisha coming to Yao.",
		"l You guys really didn't get along at all, huh. I actually thought you two were pretty compatible when I sent her there, but I guess not.",
		"b Well, looking back, I can see that I was a little immature as well. I could've been a bit more of an adult and handled her idiosyncrasies a bit more rationalely. I'd say about 20% of it was my fault.",
		"l Huh? 20%? From my perspective, it was 50/50.",
		"b What? Come on, it was obviously mostly Alisha's fault. How on earth are we equally to blame?",
		"l Well... basically, you started it, right?",
		"b Huh!? She insulted me first!",
		"l On accident, though. She was just trying to be nice and supportive at first, but... well, being Alisha, she screwed that up. Still, you actively meant to hurt her, didn't you?",
		"b ... okay, that may be true, but it's still mostly her fault. I'm willing to accept 30% of the blame.",
		"l What happened to being mature about this? Well, whatever.",
		"l Ultimately, when you look back at it with clear eyes, it becomes obvious that both of you had the best intentions in mind. Alisha was trying to protect you and become friends with you, while you wanted to prove yourself and help her. You were both trying to push what you thought were the best things for each other.",
		"l It's just that... man, you two just have zero compatibility.",
		"l And yet, at the same time, you somehow also get along with her better than anyone. It's crazy.",
		"b I don't even know what our relationship is anymore.",
		"l Speaking of the Alisha arc, Berserker is also introduced here. He's certainly a character, isn't he?",
		"b Indeed. He's definitely the kind of character that can only show up in a zikari story.",
		"b Did you know? Apparently, he was a last minute addition to the story. I heard that originally the Alisha arc was supposed to end with a fight between me and her, but then Berserker was added at the last minute.",
		"l Ihihihi, the production process of a Quest is truly slapped together at the last moment. Who knows what other random shit got added or cut on a whim.",
		"l Ah, speaking of the Forest of Meat part, you sure got intimate with her in that pavilion. It must have been wild, being tied together while completely naked.",
		"l I'm sure everyone was wondering what would happen if you guys ended up doing the Mana Transfer. Would that have been the start of the Alisha route?",
		"b I don't think we would've gone all the way. It's less efficient, but saliva transfer apparently also works, so it would've probably just been kissing...",
		"b Though, if it came down to it, I was ready to commit seppuku in front of Yingying.",
		"l Ahahaha, well, that's certainly the manly path. I think she would've forgiven you rather easily though, since you did it to save your lives. She's not the unreasonable type.",
		"b That's probably true. But, in terms of principle, I don't think it's good for me to think like that.",
		"l What a devout husband.",
		"b This much is just normal. Cheating isn't something to laugh at.",
		"b If a guy casually cheated on his wife while thinking 'she'll probably forgive me anyways', wouldn't he just be a pure scumbag?",
		"l Well, that's certainly true.",
		"l Though in that regard, aren't you constantly walking on thin ice, what with the girls you keep picking up... I wouldn't be surprised if Yingying snaps at you one of these days.",
		"b Huh, what was that?",
		"l Nothing! I was just thinking about what happened next. That's when the Emperor was suddenly assassinated, right?",
		"b Yeah. Well, he didn't die, though. He got his head cut off and his heart stabbed but just got back up.",
		"l That's a pretty strong immortality. Even some dead apostles aren't that tough.",
		"b I think Yingying mentioned that he's some sort of immortal sage? Is that a thing in chinese mythology?",
		"l I dunno. Ask Alisha, she's the Chinaboo.",
		"l More importantly, though, before that happened, you guys went to the public baths together, right? I'm interested in the conversation you had in there.",
		"b Huh? What conversation was that again?",
		"b ... oh. When we were talking about our type...",
		"b I'll just be frank. I don't really like that type of talk, so can we not touch on it?",
		"l All right, all right. I'll let it go. Though I guarantee you that the girls are talking about it, right now. Kyaa, I wonder which one he meant and all that.",
		"b The thought of the girls talking behind our backs does indeed scare me... Alisha better be keeping her mouth shut.",
		"l Anyways, after that, that's when Saber confessed to you, right?",
		"b Yeah... unfortunately.",
		"b Somehow or another, it seems that my ability also caused her hidden Skill to activate which made her fall in love with me.",
		"l How did that make you feel? Being confessed to is usually a joyous thing, but you...",
		"b How the hell am I supposed to be happy about that? I'm the one who made her like that, after all.",
		"l If you ask me, I think your treatment of her is weird. I can't tell if you treat Saber as a person or as a robot. There are times where you seem to hop back between them.",
		"b Please don't ask me stuff like that... I've already got enough on my plate already.",
		"b To be honest, I want her to be able to express her emotions and will more. But at the same time, those emotions trouble me... of all things, she had to just fall in love with me.",
		"b At the end of the arc, we managed to come to a conclusion and move forward with our relationship, but I'd be lying if I'm still not somewhat troubled by it. We're friends now, but I can't just pretend like she's not still in love with me.",
		"l During this part, we get Saber's backstory through the usual Servant dream, huh? Looking back, it's a pretty sad one.",
		"b Mn, yeah. The story of Hu Sanniang is rather tragic. All of her family was killed and then she was forced to marry one of the people who did so. It's truly worthy of the tagline: peony planted in cow dung.",
		"l I never understood that line. What does it mean?",
		"b It's a phrase used in discourse about the Water Margin to describe Saber's situation. Even though she's such a beautiful and strong warrior, she gets treated really badly in the story. Not only does her whole family die, but her husband is a total loser. It's like taking a beautiful flower and planting in poo, completely wasting its beauty.",
		"l Ah, so basically it's saying that she deserves better. In that case, do you think that she's been treated poorly in LBRP?",
		"b Is there any treatment worse than being Mind Broken?",
		"l Fair enough.",
		"l Anyways, after that, the main thing is the battle with Demonic Assassin, right? That sure was a tough fight.",
		"b Yeah. For once, we actually had a full complete Servant battle. Crazy, isn't it? Who'd have thought that this quest with Servants could actually have Servant battles?",
		"l Eh, was that really the first and only Servant fight in the Quest? That can't be... no wait, you're right.",
		"b LBRP is many things, but it's definitely not a battle shonen. I wonder when we'll get another Servant fight...",
		"l Even so, I think the fight was pretty interesting. Demonic Assassin had a lot of cool abilities. It definitely kept you on your toes.",
		"b Yeah, it's like she always had another trick up her sleeve. I'm not even entirely convinced she's shown us everything she can do.",
		"b But luckily, Saber was able to deal with her. It's hard to remember since she doesn't speak up much, so I forget that she's lowkey the smartest person on our team.",
		"l Brains, brawn, and beauty, huh. You really ended up picking up one hell of a Servant. Wanna trade?",
		"b Don't say that. Archer's gonna beat you up, again.",
		"l Sh-she's not here is she?",
		"b You are so whipped...",
		"l Well, anyways, with that, we end up going into the current arc, huh? That's more or less about it when it comes to things you did inside your Lostbelt.",
		"b Yeah, I guess that's basically it. So? After all that, do you now understand my accomplishments?",
		"l Mm, I guess I do. You did do a lot. It was a tale full of twists and turns worthy of reading. However...",
		"l Was there a single thing you just mentioned that didn't involve adding another cute girl to your team and improving your relationship with one of them?",
		"b Eh? Uhhh...",
		"b Shit.",
		"l I rest my case. From now on, the Quest will be renamed to Harem Raising Project.",
		"b How did it end up like this...? I just wanted to manage a Lostbelt and prove that I could save the world too...",
		
		"l So, anyways, I do believe this means I win our bet. And that means you have to do whatever I say!",
		"b W-wait, hold on. I never agreed to this. You said you'd do whatever I want if I could prove otherwise, but I never said the same.",
		"l Come now. It was an implicit agreement. Surely, you didn't expect to enter a gamble without consequences.",
		"b Grrr... what are you planning?",
		"l Well, let's see... what should be your punishment game? I'd like it to be something fun.",
		"l I've got it. Send an embarassing message to someone.",
		"b Eh? An embarassing message? What's up with that?",
		"l Something that'll hurt your soul when you press the send button.",
		"l Specifically, I want you to send the following: 'I want to see you in a naked apron. Please make breakfast for me tomorrow wearing only that.'",
		"b Pffftt!",
		"b Are you trying to kill me!?!?",
		"l C'mon, go for it. I believe in you! Show off your manliness!",
		"b There's nothing manly about this! You're just trying to torture me!",
		"l I promise to apologize with you afterwards. I'll explain everything, so you don't have to worry about misunderstandings.",
		"b Mnnn... fine, I guess I have no choice. It's a bit scary, but I think I can play it off if Yingying gets it.",
		"l Oi, why are you sending it to her? Did I ever say you get to choose who you send it to?",
		"l I want you to send that text to Alisha instead.",
		"b Are you the Devil!? She's going to kill me if I do that! Even if I explain everything, I'll still die!!",
		"l Do it! Do it! Do it!",
		"b AAAAAAAAGGGGGGGGHHHHHH, FINE! I'll do it!",
		"b ...",
		"b ... I sent it.",
		"b ... Oh god, it says seen. She's already seen it.",
		"b ... she's not replying. Why isn't she replying!? Say something! Don't just leave me hanging! Is she angry? She's totally angry! AAAAAAAAHHHHHHHHHH, I'M SO DEAD!!!",

		"hide character b",
		"hide character l",

		"wait 500",
		"show character l IMG with fadeIn",
		"l Alright, everyone! That wraps up this All Cast Review! Thanks for coming! I hope you enjoyed it!",
		"l Make sure you check out the Girls' Side too to see their reaction to Ben's text!",
		"hide character l",

		"show character b IMG with fadeIn",
		"b I'm going to kill you. I'm definitely killing you after this.",
		"b Hah, anyways, thanks for checking out this commentary. I hope you'll continue to read and support Lostbelt Raising Project from hereon.",
		"b See ya next time, folks!",

		"hide character b with fadeOut",
		"wait 1000",

		'show scene chapel with fadeIn',
		"wait 1000",
		
		'jump Menu'
	],

	'Girl': [

		"show scene karaoke with fadeIn",
		"wait 1000",
		"show character s IMG with fadeIn",
		"s Hello, everyone. It's good to see you again. Welcome to the All Cast Review for Lostbelt Raising Project.",
		"s I'm the pure-hearted Shrine Maiden of Snow, Mori Shiori. I'll be in your care as always for this special character commentary.",
		"s Of course, joining me are the two heroines from Lostbelt Raising Project. Please give them a warm welcome.",
		"hide character s",
		"show character y IMG with fadeIn",
		"wait 500",
		"y Hello. I'm Yingying Andreski. I play the role of the protagonist's wife in Lostbelt Raising Project.",
		"hide character y",
		"show character a IMG with fadeIn",
		"wait 500",
		"a Ohohoho, welcome, welcome. I'm Alisha Helstrom, the true Main Heroine of Lostbelt Raising Project!",
		"hide character a",
		"show character s IMG at left with fadeIn",
		"show character y IMG with fadeIn",
		"show character a IMG at right with fadeIn",
		"s And so, the three of us will be covering the alternative commentary track for LBRP. Thank you for having us.",
		"y I hope to do my best to provide insightful and entertaining commentary for everyone. Please be patient with me.",
		"a That said, why is it just us? Shouldn't Bengshan be here too?",
		"s Actually, it seems that the LBRP Review is being split into a boys part and a girls part. It's probably because it's too big to cover in just one session.",
		"s Originally, it was supposed to be you two and Bianca, but she couldn't make it for story reasons, so I came to take her place. I hope you don't mind me being here despite not being in the actual story.",
		"y Of course not. You're our honored Senpai, so we are grateful for you taking your time to join us. I hope you'll continue to instruct us with your experience.",
		"s How polite. It's nice to see such kind-hearted heroines nowadays. In that case, shall we get started?",
		"s I've heard that the boys are taking care of all the boring story stuff, so I think we can just talk about whatever we want, as long as it's LBRP-related.",
		"a In other words, we're just here for some Girls' Talk, huh? I'm okay with that! I don't actually get to talk much with other girls after all.",
		"y I see. That does take some of the pressure off. But now I'm not sure what to talk about.",
		"a Hmmm, that's true... I really don't know what to say. It feels like I have a lot to talk about, but also I can't pick something off the top of my head.",

		"s In that case, shall we start with something I noticed earlier?",
		"s When you were introducing yourself earlier, you called yourself Yingying Andreski, right Yingying?",
		"a Oooooooohhh, I didn't even notice that!",
		"y Ah, well... yes. I don't get many chances to fully introduce myself, so I figured I'd go straight for it.",
		"s That's good. There's no shame in your married name!",
		"a Though, to be honest, it does sound kind of silly. The Chinese and Polish halves don't mesh well.",
		"y Ah, that's true. I was also thinking it sounded a little awkward and I'm also not used to my given name being first.",
		"y But still... I like it a lot.",
		"s Awwwwwww, that's so cute.",
		"a Oh, I know! In our world, a lot of Chinese people get western names based on their chinese names when they move to the west. Maybe if you had one of those, it would sound less awkward.",
		"a Hmmm, what would be a good substitute for Yingying... Irene? Erin? Hmmm...",
		"y Ah, thank you for the idea. I appreciate the thought, but I think I'll stick with Yingying.",
		"y It's the name that my parents gave to me, so I don't want to abandon it. Even if my family name is to change, I still want to be their Yingying.",
		"a Oh, I see. I understand. Sorry for that.",
		"y No, it's okay. I know you were just trying to help me out. I appreciate your consideration.",

		"s Since we're on the topic, shall we discuss that? Let's talk about Yingying's marriage.",
		"s It's rather rare for a Quest Protagonist to actually be married, so I think it's rather interesting. Not to mention, you two are such a cute couple!",
		"y Oh gosh, I'm not sure what to say. You're making me embarassed.",
		"a So what's it like, being married to that oaf? He's denser than a blackhole, so it must be pretty frustrating, right?",
		"y Oh, not at all! Camille is very considerate and very kind. There isn't a single moment where I've felt like he isn't taking my feelings into consideration. And even though he has his own troubles, he's doing his best to overcome them for my sake.",
		"y It's true that our relationship is progressing a little slower than average, but I can tell he's always doing his best to close that gap. And in the meantime, I feel like there aren't many barriers between us. It's like the wall of hesitation is mostly gone.",
		"s Indeed, I think you're probably the person Camille feels the most comfortable around. From an outsider's perspective, you two feel very earnest in your love. It's something to be treasured.",
		"y Thank you. I'm happy to hear that.",
		"a Mmmmm... sorry, is it okay if I be a little crude? I don't want to ruin the sweet mood, but I'm a little curious...",
		"s Ah, go ahead. It's just us girls after all, so let's be a little looser.",
		"a In that case, I wanted to ask as a fellow woman... your marriage seems lovely and all, but are your, um... needs being satisfied?",
		"y Ah. That. W-well... I'm not sure what to say...",
		"y Umm, I suppose I do sometimes feel a little lonely at night, having such a big bed to myself. But I know he's trying his best to clear that final hurdle, so I'm willing to wait for him as long as it takes.",
		"a Th-then, umm... are you nervous? About your f-first time? Are you scared?",
		"y Ah, well... I'm not too sure. I haven't really thought of it that much. I suppose I'm just prepared for whatever happens.",
		"y I was ready for it since our first night together, so I suppose I had made up my mind a long time ago. Though, in a way, the anticipation has made me a little more nervous now.",
		"y Actually, Assassin gave me a few special pointers just in case. She said that I should take the lead during our first time since Camille's a little timid.",
		"y To be honest, I think I'd prefer it a bit more if he took the lead, but I want to do my best to make it as painless for him as possible, so I'll do what I can.",
		"s Usually, that's the guy's role, though. Well, that just goes to show the size of your tolerance for each other.",
		"a Oh, that's right. We have the Honored Senpai here with us today! Please bestow on us your wisdom regarding this matter!",
		"a Umm, like well... how much does it hurt and what to prepare for and that kind of stuff...",
		"s Oh. Umm, I'm sorry. I'm glad you're relying on me, but I don't really have any relationship experience either. Of the three of us, Yingying's actually the most experienced, despite being the youngest.",
		"y That's strange to think about. Since I'm the youngest in the main cast, I'm used to the other girls being more experienced than me...",

		"s Speaking of experience, you've had a little bit yourself too, right, Alisha?",
		"a Huh? What are you talking about?",
		"s Well, I was just thinking that a lot of the usual romcom tropes have ended up in your court too. I mean... Camille's already seen you naked.",
		"a Pfffttttt!",
		"y Eh? I-is that true?",
		"a W-wait, wait, it's not what you think, Yingying. Nothing happened. It was just accident.",
		"a Remember that time the bath broke? That's because the idiot walked in on me while I was bathing so I accidently broke the bath in retaliation. Remember?",
		"y Oh, that's right. I forgot about that. That's a relief...",
		"s But you two were also naked together in the Forest of Meat. And you spent the night together too, with no clothes.",
		"y EH!?",
		"a Oi, Senpai, are you trying to get me killed!? I've done nothing wrong, so why do I have to get looked at like I'm a housewrecker?",
		"s Sorry, sorry, I just thought it'd be good to talk about since we're sharing our experiences.",
		"s Umm, you don't have to worry Yingying. Nothing actually happened. It was part of the enemy's trap, so they had no choice.",
		"y Oh, I see. That's a relief. Phew.",
		"y Not that I doubt Camille or anything, but I couldn't help but be shocked when such things are said out loud.",
		"a Indeed, this isn't good for the heart. You hear that, Shiori?",

		"s Sorry, sorry, I didn't think it would be too big of a deal. I just fully believed in the bond between Camille and Yingying.",
		"s But since we're all on the same page now, there is something that I wanted to ask about. It's about that night in the Forest of Meat. Specifically, it's about that choice.",
		"a That choice? Oh... you mean that one.",
		"y What are you two talking about?",
		"s For the record, Yingying, it's about a possible choice that could've happened back during the Forest of Meat section. Specifically, it was when Camille and Alisha were resting after using up a lot of power in an earlier fight.",
		"s In that situation, they were in a lot of danger and their only fighter, Alisha, was out of magical energy. At the same time, though, Camille still had energy to spare but no combat abilities. So one possible solution was for him to transfer his energy to Alisha.",
		"s And well... for magi, the most effective way to do that is through... sexual intercourse.",
		"y Wha- R-really!? How surprising, I had no idea...",
		"s Of course, nothing ended up happening. But in the end, I, as well as a lot of readers, no doubt wonder what if. So I wanted to take this chance to ask on their behalf.",
		"s Alisha, if Camille had ended up suggesting it after all, would you have gone through with it?",
		"a Mmnnn.................................................... yeah, I would.",
		"a I mean, it was a life-or-death situation. I wouldn't like it, but I'm not so stubborn to turn down what might've been our only way to survive. My life is the most important thing to me, after all.",
		"s I see. Then, if that happened, how would you have felt, Yingying?",
		"s Would you have been mad at Camille for cheating on you?",
		"y No, I don't think I would be mad. In that situation, it would be silly to blame him. I don't want him to die either, after all. I think I would've understood why he did it and just be glad that he made it home safely.",
		"a Phew. Yandere route avoided.",
		"y That said, I can't say that I would've been completely emotionless and rational about it. I think... at the very least, hearing about that might've made me a little more impatient.",
		"s Impatient? Ah, you mean you would've been even more eager to tie the knot with him, since he already did it with someone else.",
		"y Yes. I think I would feel a little jealous and restless about the situation.",
		"y But that's just a hypothetical. It's hard to know exactly how I would've reacted. At the same time, I'm now happy that such a thing didn't occur.",
		"a Tell me about it. I don't want to give my precious first time to that loaf either. It's really good that we managed to dodge that H-scene.",
		"s Well, this has been very interesting and illuminating, if a little awkward. Thanks for your candid responses.",

		"s How about a change of pace? Here's a fun fact from the cutting room floor: originally, it was planned for Camille to have two wives.",
		"y Eh? Really?",
		"a Wow! Hmmm...? Oh... oh, I see. Yeah, I was wondering about that.",
		"y W-what is it?",
		"a You see, in the original legend of Emperor Yao from our world, as part of the test, he made Shun marry two of his daughters, not one. So if it were following the legend, Bengshan should've married two princesses, not just you.",
		"y Eh? No way, I never knew about that.",
		"s Well, that's just an old draft idea. It was probably removed for numerous reasons, one of which being that Yao is stricly monogamous unlike ancient China.",
		"s Still, I thought it was rather interesting. How would you feel about that, Yingying, if back then Camille also married another Imperial Princess alongside you?",
		"y Ummm... I'm sorry, I just really can't imagine it.",
		"y And, I know that our worlds have different customs, but I'm not really sure how someone could have two wives... isn't marriage supposed to be one man and one woman? How would it work otherwise?",
		"s Oh dear. I'm sorry, I didn't account for the difference in cultures when I asked.",
		"a F-for the record, how do you feel about same sex relationships?",
		"y Same sex... How would that work? You can't have children to fulfill your civic duty then.",
		"s Okay, we're touching on some pretty heavy cultural differences, so let's quickly abort before this gets awkward.",
		"a Speaking of abort, what do you think about-",
		"s Alisha, no!",
		"a I'm too curious, don't stop me!",
		"s ALISHA, NO!!!",

		"show scene karaoke with fadeIn duration 1s",
		"wait 1000",
		"show character s IMG at left with fadeIn",
		"show character y IMG with fadeIn",
		"show character a IMG at right with fadeIn",
		"wait 500",
		"s So now that we've all calmed down, why don't we move to another topic?",
		"s How about we talk about some of the characters in LBRP? I'd like to hear about your thoughts on some of the other cast members.",
		"a That sounds fun! Ask away.",
		"y I'll be happy to share my thoughts too. Everyone has been very kind and deserving of praise.",
		
		"s In that case, shall we start with the elephant in the room? What do you two think about Camille?",
		"y Well... he is my husband, after all. I think he's a very lovely and amazing person.",
		"a He's a stubborn and stupid super idiot. But well, he can be reliable at times.",
		"a Well, obviously, I would've been the superior protagonist, but I suppose Bengshan's a close second.",
		"y As a protagonist, I don't think anyone else would've been better suited for the story than him. In a way, one could say that LBRP is primarily the story of Camille Andreski.",
		"s What would you say you like about him the most?",
		"y W-well... I like how considerate he is. I feel like he's always thinking about other people and taking their needs into consideration. He doesn't really judge other people and instead tries to see their point of view. I think that's very nice of him.",
		"a Hmph. I guess it's good how honest he is. He's not really the type to emotionally manipulate someone and he's really direct when he doesn't like someone. You never really need to put your guard up around him.",
		"y Oh, if I'm allowed to say something else, I also like how gentle he is. A lot of similar protagonists can be rather violent or merciless towards their enemies. Just angering them or doing them wrong can make one a target for brutal retribution. But Camille is ultimately really gentle. He gets angry pretty often, but I don't think that anger really translates to violence. I think hurting other people often ends up hurting himself even more.",

		"s Then, moving on, what about Assassin?",
		"y She's wonderful. Intelligent, kind, and cheerful, she's a very helpful and reliable person. I'm put in a lot more ease knowing that someone like her is always by Camille's side.",
		"a Every Servant has their uses and Assassin's is pretty clear. She's useless in battle, but she's vital to Bengshan's mental and emotional stability. If Saber's his physical crutch, I'm sure Assassin is his mental one.",

		"s Speaking of which, what do you think about Saber?",
		"y She's a little cold, but I don't think she's a bad person. She seems very smart and well-mannered. I'm glad that such a person is protecting Camille from harm.",
		"a I think she's a pretty interesting case. In many ways, she feels like an extension of Bengshan rather than completlely being her own character. As his strongest Servant, she acts as his arm in conflict and she's also a direct result of his traumas. One can see why she's an awkward sort of character.",
		"s What do you think about the fact that she's in love with Camille?",
		"y Ah, well... as his wife, I can't exactly accept her feelings completely. But as someone who shares her love, I do sympathize with her a bit. Either way, I believe in my husband, so I'm not too worried.",
		"y And well... I'm not too upset about the fact.",
		"a Ah, so it's true that some girls like it when their boyfriend is a little popular.",
		"y I-I don't know about that. I just understand that my husband is very attractive, so it's fair if other women were to be charmed by him.",
		"a What part of that blockhead is supposed to be attractive?",

		"s What about Rider? What do you think about her?",
		"a Hm, she's a pretty tragic case. A Servant who wants a happy ending when such a thing is antithetical to her nature. It's definitely a complicated topic that adds quite a bit of spice to things.",
		"y That's... I'm sorry, but I'm not very fond of her...",
		"s Oh, that's right. The two of you butted heads back on Level 2.",
		"y Yes... I'm sorry, but I can't really agree with her ideologies. And I think she's a bit of a bad influence. I know that Camille appreciates her help, but I'd prefer it if we could associate with her less.",
		"a Hmmm, that's a pretty fair. Saber's an exception since she's Bengshan's Servant, but I can understand why you wouldn't get along with any Chaotic-alignment Servant.",

		"s Then what about Berserker? He's a Lawful-type.",
		"a Well yeah, but... he's Berserker.",
		"a He's crazy, to put it lightly. While I'm glad that he's our ally rather than our enemy, since he can actually be pretty scary, he's not exactly helpful or easy to deal with. Everything out of his mouth is pure nonsense.",
		"y I actually haven't interacted with him much. Camille told me to stay far away from him.",
		"a As he should. That man is definitely not someone you want near your loved ones.",

		"s Then finally, the last one is how do you feel about each other?",
		"y Oh, um... I'm not sure what to say.",
		"y Thank you for being such good friends with Camille, I suppose. I feel like his spirits are always raised whenever he's trading banter with you and that makes me very grateful. Thank you, Alisha.",
		"a Eh? What's with this? Stop it, you're making me feel weird. I-It's not like I'm really doing it for any greater reason or anything, it's just that that idiot needs someone to teach him a lesson, that's all.",
		"a But well, I guess I'm grateful to you too. Your cooking's great and you're always helpful whenever I ask you for something. And when I need it, you give me a lot of space. It's very comfortable living under the same roof as you.",
		"a I can see why that idiot is so smitten with you. You're way too good for him.",
		"y Thank you. Though I don't think I'm too good for him or anything, it does mean a lot to hear that from you. I hope we can continue to get along from hereon.",
		"s Awww, how sweet. You two are such cute friends!",

		"n Bzzzzzt!",
		"a Hm? Oh, I just got a text from Bengshan. What weird timing. Maybe the boys just wrapped up their session.",
		"a Let's see, what did he say... eh?",
		"y Hm, what's wrong? What did Camille say... ah.",
		"n 「I want to see you in a naked apron. Please make breakfast for me tomorrow wearing only that.」",
		"y Wh-wh-what is this, Alisha? Wha-wha-wha-!",
		"a I-I-I don't know! What the hell is that idiot thinking!?!?",
		"s Ara. That is... concerning.",
		"a Wh-what do I do? How am I supposed to reply to that? N-naked apron? He wants to see me in a naked apron!? Awawawawa, what do I do?",
		"y A-A-Alisha, um, is there something you haven't told me about the two of you after all?",
		"a No, no, of course not. There's nothing going on!",
		"y But he hasn't even asked me for a naked apron yet! He hasn't even seen me naked yet, either!",
		"a I don't know what's going on either! Ask him!",
		"s Ummm... why don't we all calm down? Maybe there's been some sort of misunderstanding.",
		"s For example, maybe he just sent that message to the wrong person. Maybe he meant to send it to Yingying or something and just clicked wrong.",
		"y I see. That would make more sense.",
		"a That's right. That does solve a lot of things. I mean, sending this to me is just harassment, but it's flirting if he meant to send it to Yingying.",
		"y But he's never told me that type of stuff before...",
		"s Well, there always has to be a first time. Maybe he's just ready to take the next step in your relationship.",
		"y Hmm... okay. Just in case, let's go ask him what he meant in-person. Right now. Together.",
		"a Good idea. Let's go! If he says anything dumb, I'll blast him!",
		"hide character y with fadeOutRight",
		"hide character a with fadeOutRight",
		"wait 1000",
		"s Ah. They're gone.",
		"s That man might die one of these days...",
		"hide character s",
		"wait 500",
		"show character s IMG with fadeIn",
		"s Well, this has certainly been an interesting review session. I guess we'll have to call it here.",
		"s Thank you for tuning in to this All Cast Review for Lostbelt Raising Project.",
		"s Bye bye!",

		"hide character s with fadeOut",
		"wait 1000",

		'show scene chapel with fadeIn',
		"wait 1000",

		'jump Menu'

	],

	'LoL': [

		"show scene library with fadeIn",
		"wait 1000",
		"show character s IMG with fadeIn",
		"wait 500",
		"s Hello, everyone. Welcome to the All Cast Review for Language of Love.",
		"s I'm Mori Shiori from Fate/Reclamation, here today to help bring you the character commentary for the short story, Language of Love.",
		"hide character s with fadeOut",
		"wait 500",
		"show character z IMG with fadeIn",
		"z Yo. I'm the cool-headed, cold hearted Berserker-class Servant from Fate/Nacht der Welt. You can just call me Noelle.",
		"hide character z",
		"show character s IMG at left with fadeIn",
		"show character z IMG at right with fadeIn",
		"s This time around, since the source material is a love-themed story, the two of us have been called in to commentate as experts on love.",
		"z It couldn't be helped since there aren't a lot of original characters in LoL, after all.",
		"z We wanted to bring in the main heroine, Canda, but her licensing fees are too expensive.",
		"s With that said, it's about time you introduce yourself too, Ernest.",
		"show character e IMG with fadeIn",
		"e H-hello... I'm Ernest Helmingham, the main character of Language of Love. It's an honor to be here.",
		"e I'm not very used to speaking, so I may make some mistakes. I hope everyone will treat me kindly.",
		"s Yes, everyone, we managed to drag Ernest out of his hiding hole to come join us today for this special celebration. Isn't that great? In the end, we just can't do this without the main character himself.",
		"z I'm not sure how good he'll be at commentary though...",
		"e I'm sorry. I'll do my best...",
		
		"s So we're here today to talk about Language of Love. What did you think about it, Noelle? Did you like it?",
		"z Hmm... well, it's surprisingly refreshing. Somehow, despite being in a world of magic and death, it still managed to be an orthodox story about adolescent love.",
		"e Oh, gosh. You're making me blush...",
		"z I wasn't really praising you, though.",
		"e Ohh... sorry...",
		"s Are you nervous right now, Ernest? Are you the type who's bad around girls like a certain tracksuit-wearing protagonist?",
		"e Rather than girls, it's just people in general... I'm really regretting the fact that Candis isn't here right now.",
		"z Latching onto your girlfriend when you're scared, huh. How sweet.",
		"s Ehe, I'm sure she'd be happy to hear that.",
		"e N-no, it's not like that. To begin with, we're just friends.",
		"z Sure, sure. I didn't realize this story was actually called Language of Friendship.",
		"s Well, it is true that it ends with them starting as friends. Who knows how their relationship progresses from there.",
		"z They'll be dating in a year and married in 3. I can already see it.",
		"e I told you, it's not like that!",
		"s Ah, he finally raised his voice. I guess that means we're ready to get into the thick of things.",

		"s Since it's a short story, we can go into a bit of deatil here. How about we go chapter by chapter?",
		"s Starting from Chapter One, after a nice, poetic beginning about Ernest's feelings, the story proper starts in early February with Ernest announcing his intentnions to confess to Canda.",
		"z Why'd you decide it then? Was it because you know Valentine's was coming up or was it just chance?",
		"e W-well, I didn't really plan for Valentine's. It just happened to be then that I decided to confess to her.",
		"s I see. You couldn't bear it anymore and had to confess to her, huh.",
		"e Huh? Bear it?",
		"z What are you talking about, Shiori?",
		"s Well, you know. When you think about it, a confession is basically a cry for mercy.",
		"s A love confession happens when a person can no longer bear the bottled up feelings that they've kept within and need to release them. And when they do so, they relinquish responsibility for their feelings and place them in the court of the person they confessed to, asking them to release them from the burden of their love.",
		"s Whether it is acceptance or rejection, the answer they get will put an end to the anguish of their unrequited love. In most cases, people don't actually confess to let the other person know about their feelings, but rather to free themselves from their feelings being unknown. Because their current relationship is too painful, they purposefully cut it off by making a confession.",
		"s It was the same for you too, right Ernest? Even though you already knew you would get rejected, you confessed because that was preferable to holding onto your feelings forever.",
		"e Ah... yeah, that's right.",
		"e I couldn't bear not getting any closure for my first love, so I decided to make my feelings known to her. I knew I would be rejected, but I went through with it anyways.",
		"s And hey, it actually worked out. You got to become friends with her! Congrats!",
		"e Ah, thank you...",

		"z The main plot of Chapter 1 is you getting other people to help you out with your confession, right?",
		"e That's right. I've never really done anything like that before, so I ended up asking other people for help. Both Johannes and Mr. Nomikata were very helpful. I'm eternally grateful for their assistance.",
		"z Both of them refused to help you in the beginning, though.",
		"e Well, it couldn't be helped. It was a tall task, after all. I had to do everything I could to get Mr. Nomikata on my side.",
		"z Including stripping, apparently... why did you think that was a good idea?",
		"e I, uh, just wanted to show my sincerity. Y'know, showing him that I had nothing to hide.",
		"z I see. That's a very good reason. You have the right idea, you should keep doing that.",
		"s Umm, you two, stripping isn't a normal thing to do, you know. I know you're fellow nudist buddies, but please remember that indecency laws exist.",

		"s Speaking of Seigi, at the time, this was the oldest depiction of him in a proper story, huh? Though he's an adult in Fimbulwinter, here we get to actually see him in his element at home.",
		"s In the end, though, he only ends up agreeing to help solely for the money...",
		"z Providing for a family is expensive after all. He's doesn't have any special skills, so it's no wonder he's struggling for cash. He's never been the rich noble type.",
		"s Didn't he inherit a massive, multi-national corporation?",
		"z I'm not sure how much of that furry money he actually ends up getting. Either way, it's that scene that really makes you go 'ah, so he's finally become an adult, huh'.",
		"s How sad.",

		"z Chapter Two is where we really get into things. You end up getting made to try to talk to Canda in person and that goes about as well as you'd expect.",
		"e Ah, well... in the end, I'm just really not good at talking. Well, if it's in a professional setting, I can manage, but private stuff is just nerve-wrecking.",
		"s Introverts certainly have a habit of overthinking things before going into conversations. I'm a little shy myself, so I can understand that.",
		"z Maybe you should've gone in naked. That would've shown them that you were an open and harmless person.",
		"s No, I'm pretty sure that would've made them think of him as a dangerous pervert. Please stop trying to convert him towards your nudist ideologies.",
		"z Is it just me or is it too hot in here? I'm an ice-type girl, so I can't stand it if the AC isn't on high. Can't be helped, I guess I'll strip.",
		"s Noelle!",
		"e ...",
		"z Ah, he's covering his eyes with his hands.",
		"s He's probably thinking that it's wrong for him to see any other girls naked other than Canda-chan. How cute.",
		"s Ah, Ernest, you can open your eyes now. No one's naked.",
		"e Ah, okay... p-please refrain from such jokes, it's not good for my heart.",
		"z Fine, fine. I'll restrain myself.",

		"z So, after talking to her failed, you decided to try confessing via love letter, huh. Interesting idea.",
		"s Hmm, nowadays, confessing in person is typically considered the gold standard, but love letters aren't bad either, especially for bookish types.",
		"s They let you say a lot more and they eliminate any communication failure due to anxiety. Furthermore, if all goes well, the letter itself becomes a nice souvenir of the moment where your relationship began.",
		"e Ummmm, just for reference, how would you two like to be confessed to? I really don't know about these kinds of things...",
		"s Hmm, I'm not sure. For me, I think I don't need anything dramatic or fancy. I think the important thing is that I'd want him to convey how serious and sincere he's being. If he isn't taking it seriously, I won't be able to either.",
		"z Personally, I don't want to be confessed to at all.",
		"s Really? I thought all girls dreamed of being proposed to by the guy of their dreams.",
		"z Well, if I'm being confessed to, it's like I've lost the initiative, right? I can't accept that. I'm definitely the one who'll do the confessing and I won't take no for an answer either.",
		"s How strong-willed... well, I'm sure there are plenty of people who actually like that. The ones who like being dragged around by a girl, that is.",
		"e I totally understand that feeling. Part of me does wish for someone else to take the lead in stuff like this.",
		"z Etherauletta doesn't seem like the leading-type though. Too bad.",
		"s Do your best to lead Canda-chan, Ernest! Show off your manliness.",
		"e I-I'll try my best...",

		"z Oh yeah, in Chapter Two, we also get the surprising reveal that this guy is actually part of the Lord's family the whole time.",
		"s That's right. I was totally surprised. I never suspected that Ernest would be someone important. He seemed like just a regular everyman.",
		"e No, no, I'm really not that special. I'm just a Lord Candidate in name-only. In everything else, I'm mediocre, if not below average.",
		"s To be honest, I'm still not completely sure on some of those details. Why does Canda-chan have to marry you to become a Lord?",
		"e Eh? Uhh... sorry, I'm actually not that sure myself. I'm not too good at political stuff...",
		"z ... oh, wait, do I have to be the one to explain?",
		"s Please and thank you.",
		"e Hold on. Let me take notes.",
		"z Haah, fine. Guess it can't be helped.",
		"z Basically, Lords like to keep power within their family as much as possible, as do the monarchs of old. Rather than a single term, they prefer to aim for generational power and create a dynasty. This is especially true for magi since they care so much about their families.",
		"s Oh, that's true. Magi research magecraft for the sake of their family, rather than themselves. So it makes sense that they'd prioritize giving power to the next generation of family.",
		"s Hm? But wait, wouldn't that make it difficult for Canda to become the next Lord? Even if she marries into the family, it's too late for her to take the Crest.",
		"z Well, that's just one of the comprimises that Lords have to make. While it'd be ideal for them to always just pass it on to their child, in the end, the role of Lord requires talent and skill. If it happens that the current heir of the family isn't worthy, they look into bringing someone else into the family to carry on the name instead.",
		"z Remember how the El-melloi made Waver join the family to become Lord while Reines wasn't ready yet? It's something like that. In Canda's case, the Lord Crest will probably go to her child who'll also be groomed to hopefully become the next Lord.",
		"s I see, that makes sense! Ah, but wait, in that case, the title could still basically go to anyone with enough talent, right? Then why go through the trouble of marrying into the family?",
		"z It's just a clever ploy to increase the security of one's rule and smoothen the transition of power through gatekeeping.",
		"z As a basic rule, the more open power is to being taken, the more unstable a rulership and the more chaotic the transition of power. Imagine if in a kingdom, everytime the king dies, anyone in the country has a chance to become the next king. What do you think would happen?",
		"e Hmm... it'd probably be a mad scramble for power.",
		"z That's right. It'll be like that one TV show, uh... Gate of Thrones? Where a bunch of different people are fighting over who gets to sit on the throne at the end.",
		"z If, on the other hand, it were a rule that only the family of the deceased King could become the next ruler, it'd be a lot less chaotic, right? Most people wouldn't have a chance at the throne, so fighting over it is minimized.",
		"s Oh, I see. The rule's set up so that outsiders don't get any funny ideas about trying to steal the throne for themselves. As long as they're outside the family, they can't overturn that rule and so can't become a Lord. And the Lord is the one who gets to decide who gets to join the family, so he can keep unwanted outsiders out.",
		"z Yup. It also serves to discourage assassinations too, since even if someone kills the Lord, they won't be able to get the Throne without being part of the family. Well, that still means other family members can kill the Lord, but that's another matter.",
		"z If there was any mistake Kayneth made as a magus in Fate/Zero, it was not preparing a direct successor before the war. Because of that, when he died, the power was split up amongst the many branch families, leaving Reines with a severely weakened throne. If he had arranged for everything to automatically go to Reines when he died, the El-Melloi would not be in shambles.",
		"s I see. So that's why Canda-chan has to marry Ernest.",
		"z Well, technically, she just has to marry an Astaire. There are other branch families, so it doesn't have to be Ernest...",
		"s Eh? No way, that's no good. If she has to marry someone, I'd rather it be Ernest. I don't want to see her ending up with some random noble who doesn't even love her.",
		"s Okay, Ernest, go and propose to Canda-chan, right now. Quickly, before some other guy gets his hands on her!",
		"e There's no way I can do that! Don't ask for the impossible!",
		"s Are you saying you're okay with Canda-chan marrying someone else? It's for her happiness!",
		"z Why are you so invested in this?",
		"s I just want my ship to set sail!",
		"z This is why romance novel readers are a pain...",

		"z Let's just move on. Chapter 3 picks up after Ernest learns about Canda's family situation and...",
		"z Oh right. It's the stalking chapter.",
		"s ...",
		"z ...",
		"e ...",
		"e ... I'm sorry.",
		"z As long as you understand.",
		"s The crux of this chapter is more or less focused on a single aspect. Both while stalking Canda-chan and talking to Seigi, the question on Ernest's mind is whether he is worthy of loving Canda-chan.",
		"e Yeah, that's basically it. After learning just how amazing Canda was last chapter, I was wondering if someone like me really deserved to entertain thoughts of love for her. Then, there's the talk with Elliwyn which made me realize that Candis doesn't like being confessed to, so I was really doubting whether I should go through with the plan or not.",
		"e I realized how shallow and superficial my love was and how selfish I was for loving her. In the end, I was only ever thinking about myself, selfishly falling in love who didn't even know me that well. When I realized that, I felt like I was the worst.",
		"s Luckily though, Seigi-san managed to talk you out of it. Just as falling in love with her was selfish, falling out of love with her on your own was just as selfish so you should see things through and confess to her anyways. How romantic.",
		"z After the shenanigans from earlier, Seigi finally gets a chance to act cool and show off the strength of his newfound adultness. For once, he actually seems like a wise person.",
		"s When he's talking about his old relationship, he's talking about Yorkie-san, right?",
		"z I think so, yeah. I guess it means he still isn't completely over it.",
		"s Even after everything is settled, the scars of regret never fade away, huh. If Ernest decided not to confess after all, I'm sure he would've carried the same regret for the rest of his life. What a nice lesson.",
		"e Ah, yes. Mr. Nomikata really helped me out a lot. His title of #1 Playboy isn't for show.",
		"s Ehehe, that's still funny to me.",

		"z Speaking of crossover characters, Lestari also got a spotlight in this chapter. After teasing the hell out of Ernest last time, we get to see just how much she genuinely cares for Canda.",
		"z In the end, after you become friends with Canda, how's your relationship with Lestari now? Did you two make up?",
		"e Eh? Well, it's hard to say. I guess she still feels like a friend of a friend to me. I can't exactly just casually join in on their girls' group after all.",
		"e While I understand that she does the things she does to protect Candis, I do wish she'd be just a little nicer to me...",

		"s Speaking of people who aren't nice to Ernest, Lior-chan also gets to show up in this chapter.",
		"z Yeah, trying to kill the man.",
		"s Are there that many assassins at the Clock Tower?",
		"z Well, yeah, basically. It's not exactly a common occurence, but it's enough that you wouldn't be surprised if one day someone in your class suddenly doesn't show up anymore.",
		"e Even someone important like me is prepared to get assassinated at any time, so it can happen whenever. I guess that's why even I had to take self-defense class.",
		"s Ah, that's right. Ernest barely passed self-defense class. But... I heard that Lior-chan didn't. So does that mean that Ernest is actually stronger than Lior?",
		"z Sounds right to me. Maybe he should've just fought back instead of running away.",
		"e Ehh, no way, I don't want to fight anyone. And I don't think that's how that works...",

		"z Anyways, reaching Chapter 4, we finally make it to the grand finale and the confession that we've been building up to.",
		"s And it completely bombs thanks to a certain angel kouhai!",
		"e Un... how embarassing...",
		"s While Ernest was knocked out, though, we finally get to learn the true meaning behind his love. And it's surprisingly profound.",
		"z The ennobling power of love, huh. It's a tale as old as time.",
		"z Though I doubt anyone who sees this nervous wreck could've guessed that he used to be a cold-hearted anti-social jerk.",
		"e I'm sorry, I'm sorry, I'm sorry...",
		"s That said, I think it's those ideals that make him a good fit for Canda-chan.",
		"e Eh?",
		"s Canda-chan is bothered because people keep putting her on a pedestal because of her abilities, right? But, in the end, Ernest is someone who would never do that. He will never admire her nor envy her. All he wants to do is understand her.",
		"z Isn't the act of understanding someone else hubris? As Ernest himself points out in the story, it's impossible to truly understand someone else. Saying that you do is just arrogant projection.",
		"s Indeed. When we admire or loathe other people, we are actually lying to ourselves. We are erasing the person's true self to further our own purposes. In a way, you could call it a form of killing the other person's 'self'.",
		"s This isn't a bad thing, though. Everyone in their lives does it at some point. Because we can only see a part of a person's truth, we have to fill in the rest with our assumptions and presumptions. By admiring people who are good, we become better people. By loathing people who are bad, we learn not to be bad. It is by ignoring the truth that we can move towards the ideal.",
		"s But for Canda, who stands in the eye of everyone, she has been admired and envied countless times. Her self has been killed by others over and over again. I'm sure that must be painful for her. In a sense, her excellence makes her a sacrifical tool for the betterment of the world.",
		"s Ernest, though, hates that fact of life more than anything. At the cost of his own self, he would never sacrifice another person's self by admiring them. That's why I'm sure that he, more than anyone else, would never hurt Canda-chan with lies.",
		"z That's a lot of words to just basically say that he's a nice guy.",
		"s Ehe, it sounds smart when I put it this way, right?",
		"e U-ummm, thank you...?",

		"s Okay, we're running out of time, so let's cover the final part of the story: the infimary scene.",
		"z In the end, he confesses the truth of his feelings to her at last: that he fell in love with her because she was human, not because she was perfect. And he wanted to thank her for saving him. How touching.",
		"s I wonder what was going on through Canda's head at that time. She's had other people who treat her as just herself before, but this was probably the first time someone did so while also being in love with her. I bet her heart must've been racing.",
		"z Keep in mind that she just read through a twenty-page long love letter too. She must be realizing that this guy really, genuinely loves her, rather than just being after her status and power.",
		"s How sweet. It must be a reward for her being a nice person after all this time.",
		"e Oh gosh... this is so embarassing... I didn't know hearing people talk about my feelings out loud would be so embarassing.",
		"z In the end, they agree to become friends. I think that's a nice start. It would've been a bit of a stretch to start dating off the bat, but becoming friends shows that she's legitimately interested in this weirdo who just confessed to her.",
		"s Oh, but look carefully at this line. She says 'I still can’t date you right now'. That means she can in the future, right?",
		"z That's a bit of a stretch too, but I suppose you could interpret it that way.",
		"s Kyaaa, how cute!",
		"e ... dying... this is killing me...",

		"s Ah, sorry, sorry, I forgot you were here, Ernest. I guess this kind of talk is too much of a direct hit for you.",
		"s Why don't we wrap things up now? As some parting words, let's both give Ernest some advice on his relationship.",
		"e Eh? I-it's okay, you guys don't have to go that far.",
		"z Well, sure, I guess we can do this. I'll start then.",
		"z Let's see... I think it's okay to be more confident. You're probably worried that your relationship with Canda may interfere with her other friendships, especially since some of her friends aren't very fond of you, but don't fret too much. How she manages her relationships is up to Canda alone. Don't double-guess your feelings and just keep being the best friend you can.",
		"e Ah, I see... thank you for your advice. I'll keep that in mind.",
		"s As for me, I'll say that it's okay to be more aggressive. Canda's the hesitant-type, so you should try to lead her more. Girls like her actually like to be approached a little forcefully.",
		"s You don't have to be a casanova or anything, but you don't have to double-check and double-guess everything about your date plans or something like that. You're the guy so you should be willing to just take charge every now and then.",
		"e Ah, umm... okay. I'll do my best.",

		"s Well, then, that's all for this All Cast Review. Thanks for coming, everyone! See you in another work soon!",
		"z Bye bye. Let's meet again soon.",
		"e Thank you for everything. Farewell!",

		"hide character s with fadeOut",
		"hide character z with fadeOut",
		"hide character e with fadeOut",
		"wait 1000",

		'show scene chapel with fadeIn',
		"wait 1000",

		'jump Menu'
	],

	'TULPA': [
		"show scene onsen with fadeIn",
		"wait 1000",
		"show character z IMG with fadeIn",
		"z Welcome to the All Cast Review for Tokyo Urban Legends and Paranormal Activities.",
		"z Nice to meet you. I'm the Berserker-class Servant from Fate/Nacht der Welt. For numerous reasons, I'll be the one hosting the commentary track this time around.",
		"z Of course, I'm not alone. The two heroines are here as well. Come on, you two, get in here.",
		"hide character z",
		"show character sa IMG with fadeIn",
		"wait 500",
		"sa H-hey there. I'm the Lover-archetype Tulpamancer, Sakura Sayo. I'm honored to be here.",
		"hide character sa",
		"show character al IMG with fadeIn",
		"al Hmph. I'm Alyssa Wainwright, the Hero-archetype Tulpamancer. Since I was asked nicely, I figured I could show up and grace this place with my presence.",
		"hide character al",
		"wait 500",

		"show character z IMG at right with fadeIn",
		"show character sa IMG with fadeIn",
		"show character al IMG at left with fadeIn",
		"wait 500",
		"z Well then, it seems we have a full house. This time it looks like it's just the three of us, so let's take it easy and get to know each other.",
		"al Sorry. That's great and all, but I have an important question.",
		"al Why are we in an onsen for this? Is this really the best place to do commentary?",
		"z Why not? It's better to be relaxed, right? There's no rule that says we can't do an All Cast Review in a hot spring.",
		"z By the way, Shiori was supposed to host this section, but she suddenly said that she didn't want to bare her skin in front of anyone other than her future husband, so I ended up here in her place. Guess they figured no one was better at naked dialogue than me.",
		"sa I'm starting to feel the same way as her. Can I leave too?",
		"z It's fine, it's fine. The image shows us with clothes anyways, so it's fine.",
		"z Oh, you two both drink, right? I have some sake here. Dig in.",
		"sa This is surprisingly cultured for a foreign Servant. How do you know about drinking sake in a hot spring?",
		"z My Master is Japanese too, so I picked up a few of the finer points.",
		"al Aren't you supposed to be an ice-type girl? Shouldn't a hot spring be your weakness? Well, I mean, I am too, but...",
		"z Ah, I'm melting away... my fatigue, my worried, and even my skin is melting...",
		"sa One of those things definitely shouldn't be melted away!",

		"show scene onsen with fadeIn duration 1s",
		"wait 1000",
		"show character al IMG at left with fadeIn",
		"show character sa IMG with fadeIn",
		"show character z IMG at right with fadeIn",
		"wait 500",

		"al So, now that we're settled in, how should we do this? Are you going to ask us questions or something?",
		"z Well, TULPA's a bit too long to cover everything, part by part. We'll just have to touch on the most important topics and cover the things people want to hear about the most.",
		"sa That makes sense. So, what should we start with?",
		"z Well, if we're talking about important topics, it has to be that one, right?",
		"z Why has TULPA been on hiatus for so long?",
		"sa Pfffffft!",
		"al You're starting with that!? Don't you have any tact?",
		"z I figured it was the question that readers want to know about the most. I don't like ignoring the elephant in the room, after all.",
		"al Haah, very well. I guess I'll briefly explain what's going on with TULPA.",
		"al Well, basically... it's all Sunny's fault.",
		"z Oi, what happened to having tact?",
		"al Apparently, the author felt awkward about sharing the channel with Fate/Recursion, so he quietly backed off to let it do its thing, thinking that since it was an anniversary project, it would conclude around the time of the anniversary and that TULPA could just restart then.",
		"al And then, eventually TULPA was on hiatus for so long that it apparently felt awkward to restart it so he's kept putting it off for nearly a year now.",
		"z ... wait, isn't that just his own fault for being stupid? Sunny did nothing wrong.",
		"al Indeed. He's just an idiot.",
		"all ...",
		"sa A-anyways, let's not talk about that! We're here today to celebrate the anniversary, not to complain. Let's keep up our spirits.",
		"sa What's the next topic, Berserker? Please keep it to story-related, non-meta stuff.",
		"z Let's see... the next topic is...",
		"z So you two both totally like the same guy, right? How's that going?",
		"sa PFFFFFFFTTT!!!",
		"al Shiori! Someone call Shiori here immediately so we can have a normal conversation about our Quest!",
		"z Sheesh, over-reaction much? That was an in-story question like you asked for.",
		"sa There's such a thing as delicacy though. Now it's totally awkward because you said that.",
		"z Isn't it more awkward to have the elephant in the room hanging around? I think it's better to just address problems as you notice them.",
		"sa What a straight-forward person...",
		"z So what is it? Do you both like the main character or not?",
		"sa Isn't there something else more important to discuss? Like the characters, or the plot, or the mystery of the scenario?",
		"z Doesn't matter. Nobody cares about that shit. As a respresentative of the readers, I can assure you that the only question on people's minds right now is which route they're on.",
		"al How crude...",
		"z So what is it? Which route is the Quest heading towards?",
		"sa W-well... while a part of me still feels otherwise, I have come to terms with my feelings and my complexes as the Lover, so I think I've more or less bowed out of the fight.",
		"sa I think he and Alyssa would make a good couple, so I think I should support them both as their friend.",
		"al Oh, really? In that case, I'll take him. Thanks for your support, Sayo.",
		"sa Eh?",
		"sa Umm, wait, wait, hold on, Alyssa. Under this situations, isn't the usual pattern for us both to show consideration for each other's feelings and enter a stalemate-like situation? You know, like usual love triangle stuff.",
		"al Huh? Why? You said you're backing off, right? So it's okay for me to go out with him, right?",
		"sa Eh? Umm... m-maybe? I-I dunno, I wasn't expecting you to be so forthright with it.",
		"sa I mean, it's not really my place to get in between the two of you, but um I'm not really sure if I... I mean, if I'm okay with... well, it. And um, I... I don't...",
		"al I don't get it. Which is it? Do you want to date him or not!?",
		"sa I don't know! I don't even know anymore!",
		"sa Ahhhhhhhhh, this weird atmosphere is messing up my thoughts. I don't even know what I'm thinking about it anymore!",
		"z Wow, you two are a mess. Get a hold of yourselves.",
		"sa Shut up! You're one to talk!",
		"al Whose fault do you think this is!",
		"al Ah, that's it. I'm done here. We're not getting anything done in this atmosphere. The heat from the bath must be getting to our heads.",
		"sa Good point. I'm definitely feeling a little light-headed from the alchohol too. Let's just go.",
		"hide character al with fadeOutLeft",
		"hide character sa with fadeOutLeft",
		"wait 500",
		"z Ah, they left.",
		"z Darn, I was just about to get serious.",
		"z Oh well, whatever. Let's just hope I don't get scolded for this.",
		"hide character z",
		"wait 500",
		"show character z IMG with fadeIn",
		"z Well, I guess that's it for now, folks. Hopefully, we'll be able to have a proper session in the future.",
		"z Thanks for tuning in for now. See you next time.",

		"hide character z with fadeOut",
		"wait 1000",

		'show scene chapel with fadeIn',
		"wait 1000",

		"jump Menu"

	],

});